//old token backs
export interface StaticTokens {
    env: string
    ip_id: number
    token: string
    old_info: {
        token_info: any
        current_token_info: any
    }
    new_info: {
        enable_buyback: boolean
        token_info: any
        current_token_info: any
    }
}

export const STATIC_TOKENS: StaticTokens[] = [
    {
        env: "dev",
        ip_id: 536,
        token: "A6hf3WZEpfjCG8DQvrVaNRDb8p4DR2j81vSFuyw1LAKV",
        old_info: {
            token_info: {
                version: "v3",
                user_address: "HHfLyddQFZF7fbwuNJJWEWiKic3nRimYQHDtQvCiuyLc",
                mint: "A6hf3WZEpfjCG8DQvrVaNRDb8p4DR2j81vSFuyw1LAKV",
                bonding_curve: "7fyKTfBgBcvLrZ8kqVggWXT42rd55cL8bVrSKeWRK54P",
                bonding_curve_progress: 0,
                name: "moon",
                symbol: "moon",
                price: "0.000000519090909",
                market_cap: "519.09",
                circulating_supply: "0",
                total_supply: "1000000000",
                cover_url: "https://giggle.mypinata.cloud/ipfs/QmWEeV1nsm8qJttShSuca59zQqn1XwdR9YZZpZpSaQqNQs",
                file_url: "",
                twitter: "",
                telegram: "",
                website: "",
                status: "completed",
                signature: "4fFD8pxPSJqm3bqGoErrYXo8kPop53vtG8RTVk8rRFLfuwGBbq8rDccifksDGxux8dZ7n9X5jXzUEStJkCWor29n",
                description: "moon",
                metadata_uri: "https://giggle.mypinata.cloud/ipfs/QmcxHXHZejfUjRwMWZeuuZxxvtUbAjoht5FKp38QqSayTM",
                sequels_amount: "0",
                created_at: "2025-09-01T11:10:41.015Z",
                updated_at: "2025-09-01T11:10:55.9Z",
                visitLink: "https://front-v2.giggletest.dev/orbitans?mint=A6hf3WZEpfjCG8DQvrVaNRDb8p4DR2j81vSFuyw1LAKV",
            },
            current_token_info: {
                version: "v3",
                userAddress: "HHfLyddQFZF7fbwuNJJWEWiKic3nRimYQHDtQvCiuyLc",
                name: "moon",
                mint: "A6hf3WZEpfjCG8DQvrVaNRDb8p4DR2j81vSFuyw1LAKV",
                symbol: "moon",
                marketCap: "1898.25",
                description: "moon",
                fileUrl: "",
                coverUrl: "https://giggle.mypinata.cloud/ipfs/QmWEeV1nsm8qJttShSuca59zQqn1XwdR9YZZpZpSaQqNQs",
                twitter: "",
                telegram: "",
                website: "",
                price: "0.0000018982512667",
                on_exchange: false,
                change5m: "0",
                change1h: "0",
                change24h: "0",
                bondingCurveProgress: 0.3467971076822061,
                lastTradingTime: 0,
                tradeVolume: "532492633.657042",
                totalSupply: "1000000000",
                tradingUri:
                    "https://front-v2.giggletest.dev/orbitans?mint=A6hf3WZEpfjCG8DQvrVaNRDb8p4DR2j81vSFuyw1LAKV",
                playerUri:
                    "https://front-v2.giggletest.dev/listPlayer?mint=A6hf3WZEpfjCG8DQvrVaNRDb8p4DR2j81vSFuyw1LAKV",
                site: "plugin",
                poolType: "",
                poolAddress: "",
                trade24hSol: "14.45402",
                credit_price: 500,
                file_url: "",
                cover_url: "https://giggle.mypinata.cloud/ipfs/QmWEeV1nsm8qJttShSuca59zQqn1XwdR9YZZpZpSaQqNQs",
                market_cap: "1898.25",
                visitLink: "https://front-v2.giggletest.dev/orbitans?mint=A6hf3WZEpfjCG8DQvrVaNRDb8p4DR2j81vSFuyw1LAKV",
            },
        },
        new_info: {
            enable_buyback: false,
            token_info: {
                version: "v3",
                user_address: "CGvh7rub99xN5XNh4W5EC3njhPRUPYDB17majF44cXKu",
                mint: "4iGz2ereVGDFDBbiXqyCB6zZMr7GTTMdqpPSpJrHA68q",
                bonding_curve: "",
                bonding_curve_progress: 0,
                name: "X2C Platform Token",
                symbol: "X2C",
                price: "0.01",
                market_cap: (1000000000 * 0.01).toString(),
                circulating_supply: "0",
                total_supply: "1000000000",
                cover_url: "https://ipfs.filebase.io/ipfs/QmXHJeCoBb6kivPwepaAgqMLmJftpf59RxisZq1dJjjFWX",
                file_url: "",
                twitter: "https://x.com/X2C_Official",
                telegram: "",
                website: "https://x2c.hk",
                status: "completed",
                signature: "5VjtVctfMpyNqZy6vFnifs6X2qzWLA3ZU4bC6QwKdYxuCKBFzocEBNwtWjBbSzNyhYHktH7fwsxWocZpBjtEJfuD",
                description: "moon",
                metadata_uri: "https://ipfs.filebase.io/ipfs/QmdutGWnsuFkcYVnrdt2mTrWAvZMpDKhsX7UGsdkrYBmkp",
                sequels_amount: "0",
                created_at: "2025-09-01T11:10:41.015Z",
                updated_at: "2025-09-01T11:10:55.9Z",
                visitLink: "",
            },
            current_token_info: {
                version: "v3",
                userAddress: "CGvh7rub99xN5XNh4W5EC3njhPRUPYDB17majF44cXKu",
                name: "X2C Platform Token",
                mint: "4iGz2ereVGDFDBbiXqyCB6zZMr7GTTMdqpPSpJrHA68q",
                symbol: "X2C",
                marketCap: (1000000000 * 0.01).toString(),
                description:
                    "X2C is the platform token of the AIGC Content Exchange, enabling buy-back, creator rewards, and governance across the Giggle ecosystem.",
                fileUrl: "",
                coverUrl: "https://ipfs.filebase.io/ipfs/QmXHJeCoBb6kivPwepaAgqMLmJftpf59RxisZq1dJjjFWX",
                twitter: "https://x.com/X2C_Official",
                telegram: "",
                website: "https://x2c.hk",
                price: "0.01",
                on_exchange: false,
                change5m: "0",
                change1h: "0",
                change24h: "0",
                bondingCurveProgress: 0,
                lastTradingTime: 0,
                tradeVolume: (1000000000 * 0.01).toString(),
                totalSupply: "1000000000",
                tradingUri:
                    "https://front-v2.giggletest.dev/orbitans?mint=4iGz2ereVGDFDBbiXqyCB6zZMr7GTTMdqpPSpJrHA68q",
                playerUri:
                    "https://front-v2.giggletest.dev/listPlayer?mint=4iGz2ereVGDFDBbiXqyCB6zZMr7GTTMdqpPSpJrHA68q",
                site: "plugin",
                poolType: "",
                poolAddress: "",
                trade24hSol: "0",
                credit_price: 500,
                file_url: "",
                cover_url: "https://ipfs.filebase.io/ipfs/QmXHJeCoBb6kivPwepaAgqMLmJftpf59RxisZq1dJjjFWX",
                market_cap: (1000000000 * 0.01).toString(),
                visitLink: "https://front-v2.giggletest.dev/orbitans?mint=4iGz2ereVGDFDBbiXqyCB6zZMr7GTTMdqpPSpJrHA68q",
            },
        },
    },

    {
        env: "product",
        ip_id: 145,
        token: "5jicsjUFPCMMzWAyvStMxpPLGAsN6iFDhUXpUh3vgigg",
        old_info: {
            token_info: {
                user_address: "Hk9o6uMwPTQvnH9Bcs1FhYpndp9sy14kYnnn5x4uEMT",
                mint: "5jicsjUFPCMMzWAyvStMxpPLGAsN6iFDhUXpUh3vgigg",
                bonding_curve: "F8ksKqca3UMVeSNdShTLnsGuTpUXSrVGyVUdYCgzhL18",
                bonding_curve_progress: 0,
                name: "X2C",
                symbol: "X2C",
                price: "0.00000000463821892393321",
                market_cap: "4.64",
                circulating_supply: "0",
                total_supply: "1000000000",
                cover_url: "https://giggle.mypinata.cloud/ipfs/QmZ3xByKeFw2hbSLKTHWUZnxCamBy4BPGW1gWEEn72PFDQ",
                file_url:
                    "https://static.giggle.fun/44381e86a4cfaba4560c3ab2caa553f0019cca4afddeab32565ad6db16fd6844.mp4",
                twitter: "https://x.com/X2Chk",
                telegram: "",
                website: "https://2c.hk/",
                status: "completed",
                signature: "62oq5bdoS8fZ23JTKh1eH45DaZBRD3ETvV2x5jt7w4VbinFMR7Gz1NAe7whDtFEpYF3koqeeH99EeG31rqKb1Z3r",
                description:
                    "X2C is a globally leading AI-driven IP management platform focused on combining AI-generated content (AIGC) with innovative Web3 technologies to create new growth opportunities for the film and content industries. With support and IP licenses from numerous renowned international film companies, X2C empowers classic film IPs through tokenomics and AI-generated short dramas. The platform creates a new ecosystem where anyone can freely create, distribute, and share revenues, ensuring every creative idea has the opportunity to gain global visibility and be transformed into tangible value.",
                metadata_uri: "https://ipfs.io/ipfs/QmeLFComyrUbRH78KqAq5CRtyt6MmLTpxLJjmZLzuKqjhf",
                sequels_amount: "0",
                created_at: "2025-03-16T05:16:10.666Z",
                updated_at: "2025-03-16T05:16:24.109Z",
                visitLink: "https://giggle.fun/orbitans?mint=5jicsjUFPCMMzWAyvStMxpPLGAsN6iFDhUXpUh3vgigg",
            },
            current_token_info: {
                version: "v2",
                userAddress: "Hk9o6uMwPTQvnH9Bcs1FhYpndp9sy14kYnnn5x4uEMT",
                name: "X2C",
                mint: "5jicsjUFPCMMzWAyvStMxpPLGAsN6iFDhUXpUh3vgigg",
                symbol: "X2C",
                marketCap: "100622.3893",
                description:
                    "X2C is a globally leading AI-driven IP management platform focused on combining AI-generated content (AIGC) with innovative Web3 technologies to create new growth opportunities for the film and content industries. With support and IP licenses from numerous renowned international film companies, X2C empowers classic film IPs through tokenomics and AI-generated short dramas. The platform creates a new ecosystem where anyone can freely create, distribute, and share revenues, ensuring every creative idea has the opportunity to gain global visibility and be transformed into tangible value.",
                fileUrl:
                    "https://static.giggle.fun/44381e86a4cfaba4560c3ab2caa553f0019cca4afddeab32565ad6db16fd6844.mp4",
                coverUrl: "https://giggle.mypinata.cloud/ipfs/QmZ3xByKeFw2hbSLKTHWUZnxCamBy4BPGW1gWEEn72PFDQ",
                twitter: "https://x.com/X2Chk",
                telegram: "",
                website: "https://2c.hk/",
                price: "0.000101942380436694",
                on_exchange: true,
                change5m: "0",
                change1h: "0",
                change24h: "0",
                bondingCurveProgress: 1,
                lastTradingTime: 0,
                tradeVolume: "1296888293.881627",
                totalSupply: "1000000000",
                tradingUri: "https://giggle.pro/orbitans?mint=5jicsjUFPCMMzWAyvStMxpPLGAsN6iFDhUXpUh3vgigg",
                playerUri: "https://giggle.pro/listPlayer?mint=5jicsjUFPCMMzWAyvStMxpPLGAsN6iFDhUXpUh3vgigg",
                site: "3body",
                poolType: "CPMM",
                poolAddress: "Eb8x9aBgFHcq91eTJfF6JkTCCdNA2EXdwGVJpTnYkFrL",
                trade24hSol: "0",
                credit_price: 10000,
                file_url:
                    "https://static.giggle.fun/44381e86a4cfaba4560c3ab2caa553f0019cca4afddeab32565ad6db16fd6844.mp4",
                cover_url: "https://giggle.mypinata.cloud/ipfs/QmZ3xByKeFw2hbSLKTHWUZnxCamBy4BPGW1gWEEn72PFDQ",
                market_cap: "100622.3893",
                visitLink: "https://giggle.pro/orbitans?mint=5jicsjUFPCMMzWAyvStMxpPLGAsN6iFDhUXpUh3vgigg",
            },
        },
        new_info: {
            enable_buyback: false,
            token_info: {
                version: "v3",
                user_address: "CGvh7rub99xN5XNh4W5EC3njhPRUPYDB17majF44cXKu",
                mint: "X2CKb4so3xu5hey7nmMGio8nk3zUH8kywborbQ8nSB3",
                bonding_curve: "",
                bonding_curve_progress: 0,
                name: "X2C Platform Token",
                symbol: "X2C",
                price: "0.01",
                market_cap: (1000000000 * 0.01).toString(),
                circulating_supply: "0",
                total_supply: "1000000000",
                cover_url: "https://ipfs.filebase.io/ipfs/QmXHJeCoBb6kivPwepaAgqMLmJftpf59RxisZq1dJjjFWX",
                file_url: "",
                twitter: "https://x.com/X2C_Official",
                telegram: "",
                website: "https://x2c.hk",
                status: "completed",
                signature: "VeM48DvYxoa4n5GL7DUskj7L9zA6b8rQUaNpUKKnXuvzesvLV7MTBs88ASmD2wKaWwnM9NpvP1HPAP9nANPk3u5",
                description:
                    "X2C is the platform token of the AIGC Content Exchange, enabling buy-back, creator rewards, and governance across the Giggle ecosystem.",
                metadata_uri: "https://ipfs.filebase.io/ipfs/QmdutGWnsuFkcYVnrdt2mTrWAvZMpDKhsX7UGsdkrYBmkp",
                sequels_amount: "0",
                created_at: "2025-10-10T01:52:25.015Z",
                updated_at: "2025-10-10T01:52:25.9Z",
                visitLink: "",
            },
            current_token_info: {
                version: "v3",
                userAddress: "CGvh7rub99xN5XNh4W5EC3njhPRUPYDB17majF44cXKu",
                name: "X2C Platform Token",
                mint: "X2CKb4so3xu5hey7nmMGio8nk3zUH8kywborbQ8nSB3",
                symbol: "X2C",
                marketCap: (1000000000 * 0.01).toString(),
                description:
                    "X2C is the platform token of the AIGC Content Exchange, enabling buy-back, creator rewards, and governance across the Giggle ecosystem.",
                fileUrl: "",
                coverUrl: "https://ipfs.filebase.io/ipfs/QmXHJeCoBb6kivPwepaAgqMLmJftpf59RxisZq1dJjjFWX",
                twitter: "https://x.com/X2C_Official",
                telegram: "",
                website: "https://x2c.hk",
                price: "0.01",
                on_exchange: false,
                change5m: "0",
                change1h: "0",
                change24h: "0",
                bondingCurveProgress: 0,
                lastTradingTime: 0,
                tradeVolume: (1000000000 * 0.01).toString(),
                totalSupply: "1000000000",
                //tradingUri:
                //    "https://front-v2.giggletest.dev/orbitans?mint=4iGz2ereVGDFDBbiXqyCB6zZMr7GTTMdqpPSpJrHA68q",
                //playerUri:
                //    "https://front-v2.giggletest.dev/listPlayer?mint=4iGz2ereVGDFDBbiXqyCB6zZMr7GTTMdqpPSpJrHA68q",
                site: "plugin",
                poolType: "",
                poolAddress: "",
                trade24hSol: "0",
                credit_price: 500,
                file_url: "",
                cover_url: "https://ipfs.filebase.io/ipfs/QmXHJeCoBb6kivPwepaAgqMLmJftpf59RxisZq1dJjjFWX",
                market_cap: (1000000000 * 0.01).toString(),
                visitLink: "https://giggle.pro/orbitans?mint=X2CKb4so3xu5hey7nmMGio8nk3zUH8kywborbQ8nSB3",
            },
        },
    },
]
